name: FastAPI CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Docker-Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      
      - name: Строим образ
        run: | 
          docker-compose build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Docker-Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      

      - name: Запускаем Тесты
        run: | 
          docker-compose run --rm test
  
  deploy:
    runs-on: ubuntu-latest 
    needs: test 
    steps: 
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Trigger Render Deploy 
        run: |
          mkdir -p ../staging
          cp -r . ../staging/